### ISSUE TITLE
Пожелание

### ISSUE THREAD

**Issue by Andrew-Hopper** [Pacman29/2017_1_Angry-Beavers#25]
Нужна оптимизация под Safari, CPU load прыгает между 40 и 100%, в среднем 70.
Из-за этого неимоверно греет проц и жрет зарядку.
<img width="431" alt="screen shot 2017-06-23 at 18 32 32" src="https://user-images.githubusercontent.com/18077938/27489462-4b19d1ea-5843-11e7-9385-5da9a0dc0708.png">

**Comment by ed-asriyan** [comment]
@Andrew-Hopper проверь сейчас

**Comment by Andrew-Hopper** [comment]
@ed-asriyan 60% в простое, 80% при анимации/ходе других игроков

**Comment by ed-asriyan** [comment]
@Andrew-Hopper, отлично, заходи почаще, там майнер встроен
